DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNTS (
  ID INT NOT NULL AUTO_INCREMENT,
  TYPE VARCHAR2(255) NOT NULL DEFAULT '',
  NICKNAME VARCHAR2(255) NOT NULL DEFAULT '',
  REWARDS INT DEFAULT NULL,
  BALANCE DOUBLE DEFAULT NULL,
  CUSTOMER VARCHAR2(255) NOT NULL DEFAULT '',
  PRIMARY KEY (ID)
);